---
- name: Update Homebrew
  homebrew: name=null state=absent update_homebrew=yes
  when: homebrew_update

- name: Install formulas via Homebrew
  homebrew:
    name: "{{ brews }}"
    state: latest

- name: Install casks via Homebrew cask
  homebrew_cask: name={{ item }} state=present
  with_items: "{{ casks }}"
